name: MidnightPatch
version: '1.0-SNAPSHOT'
main: fun.mntale.midnightPatch.MidnightPatch
bootstrapper:
  - fun.mntale.midnightPatch.farming.AutoHarvestBootstrap
  - fun.mntale.midnightPatch.fishing.RecastBootstrap api-version: '1.21'
authors: [ MidnightTale_ ]
website: https://mntale.fun
folia-supported: true
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true